"""empty message

Revision ID: 07bdd4d21e24
Revises: 73e290cb35a9
Create Date: 2018-09-07 16:18:22.797985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07bdd4d21e24'
down_revision = '73e290cb35a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ItemToLending', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ItemToLending', schema=None) as batch_op:
        batch_op.drop_column('returned')

    # ### end Alembic commands ###
