"""empty message

Revision ID: 2181bdb161da
Revises: 29d8df81268e
Create Date: 2018-07-25 15:03:47.179134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2181bdb161da'
down_revision = '29d8df81268e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Settings',
    sa.Column('user', sa.String(length=190), nullable=False),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user', name=op.f('pk_Settings'))
    )
    with op.batch_alter_table('Settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Settings_user'), ['user'], unique=False)

    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_name_from_schema', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.drop_column('update_name_from_schema')

    with op.batch_alter_table('Settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Settings_user'))

    op.drop_table('Settings')
    # ### end Alembic commands ###
