"""empty message

Revision ID: 31c90acab335
Revises: 73e290cb35a9
Create Date: 2018-09-13 22:07:58.848273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c90acab335'
down_revision = '73e290cb35a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('File', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('visible_for', sa.String(length=190), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('File', schema=None) as batch_op:
        batch_op.drop_column('visible_for')
        batch_op.drop_column('file_data')

    # ### end Alembic commands ###
