"""empty message

Revision ID: 53482a1da62a
Revises: 70ab97044985
Create Date: 2019-04-18 14:15:20.648676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53482a1da62a'
down_revision = '70ab97044985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ItemToLending')
    with op.batch_alter_table('AttributeDefinition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_time', sa.Integer(), nullable=True))
        op.execute(' UPDATE "AttributeDefinition" SET "deleted_time" = 1 WHERE "AttributeDefinition"."deleted"')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('File', schema=None) as batch_op:
        batch_op.drop_index('ix_File_file_hash')

    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('due', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lending_id', sa.Integer(), nullable=True))
        op.execute(' UPDATE "Item" SET "deleted_time" = 1 WHERE "Item"."deleted"')
        batch_op.create_foreign_key(batch_op.f('fk_Item_lending_id'), 'Lending', ['lending_id'], ['id'])
        batch_op.drop_column('deleted')

    with op.batch_alter_table('ItemToAttributeDefinition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_time', sa.Integer(), nullable=True))
        op.execute(' UPDATE "ItemToAttributeDefinition" SET "deleted_time" = 1 WHERE "ItemToAttributeDefinition"."deleted"')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('ItemType', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_time', sa.Integer(), nullable=True))
        op.execute(' UPDATE "ItemType" SET "deleted_time" = 1 WHERE "ItemType"."deleted"')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('Tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_time', sa.Integer(), nullable=True))
        op.execute(' UPDATE "Tag" SET "deleted_time" = 1 WHERE "Tag"."deleted"')
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('deleted_time')

    with op.batch_alter_table('ItemType', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('deleted_time')

    with op.batch_alter_table('ItemToAttributeDefinition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('deleted_time')

    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_Item_lending_id'), type_='foreignkey')
        batch_op.drop_column('lending_id')
        batch_op.drop_column('due')
        batch_op.drop_column('deleted_time')

    with op.batch_alter_table('File', schema=None) as batch_op:
        batch_op.create_index('ix_File_file_hash', ['file_hash'], unique=False)

    with op.batch_alter_table('AttributeDefinition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('deleted_time')

    op.create_table('ItemToLending',
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('lending_id', sa.INTEGER(), nullable=False),
    sa.Column('due', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['Item.id'], ),
    sa.ForeignKeyConstraint(['lending_id'], ['Lending.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'lending_id')
    )
    # ### end Alembic commands ###
