"""empty message

Revision ID: 70ab97044985
Revises: 73e290cb35a9
Create Date: 2018-09-14 03:07:21.961058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ab97044985'
down_revision = '73e290cb35a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('File', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_for', sa.String(length=190), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('File', schema=None) as batch_op:
        batch_op.drop_column('visible_for')

    # ### end Alembic commands ###
