"""empty message

Revision ID: 73e290cb35a9
Revises: 2181bdb161da
Create Date: 2018-08-22 14:10:26.041878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e290cb35a9'
down_revision = '2181bdb161da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.create_unique_constraint('_name_type_id_uc', ['name', 'type_id'])
        batch_op.drop_constraint('uq_Item_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_Item_name', ['name'])
        batch_op.drop_constraint('_name_type_id_uc', type_='unique')

    # ### end Alembic commands ###
