"""empty message

Revision ID: b4dc44ad0f16
Revises: 70ab97044985
Create Date: 2018-09-26 16:33:24.577811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4dc44ad0f16'
down_revision = '70ab97044985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ItemToLending')
    with op.batch_alter_table('File', schema=None) as batch_op:
        batch_op.drop_index('ix_File_file_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('File', schema=None) as batch_op:
        batch_op.create_index('ix_File_file_hash', ['file_hash'], unique=False)

    op.create_table('ItemToLending',
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('lending_id', sa.INTEGER(), nullable=False),
    sa.Column('due', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['Item.id'], ),
    sa.ForeignKeyConstraint(['lending_id'], ['Lending.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'lending_id')
    )
    # ### end Alembic commands ###
